### ISSUE TITLE
Control diversity of layouts and color settings separately

### ISSUE THREAD

**Issue by KarlXing** [openai/procgen#31]
If I understand it right, there are two kinds of diversity for generalization in procgen. One is the background & object colors and another one is the layouts. Is there a way to control their diversity separately so that people can study generalization on these two topics independently? I understand there's no API for now. If I want to modify the kernel code to allow this kind of control, could you please give me some suggestions? Thank you!

**Comment by christopherhesse** [comment]
They're independent to some extent, in that you can choose to use generated assets or not.

If you are using generated assets:

* for backgrounds you can move https://github.com/openai/procgen/blob/master/procgen/src/basic-abstract-game.cpp#L749 to only run during `game_init` instead of on `game_reset`
* for objects, these appear to already be the same each time

If you use fixed assets it will choose from a few options:

* for backgrounds you can have only a single option for each of these by having only 1 entry in each of these lists: https://github.com/openai/procgen/blob/master/procgen/src/resources.cpp#L38
* for objects, you probably have to change each individual game: https://github.com/openai/procgen/blob/master/procgen/src/games/leaper.cpp#L49 and https://github.com/openai/procgen/blob/master/procgen/src/games/coinrun.cpp#L69 for instance, so that for each type there is only a single image available.
   * unfortunately, some of the assets names are overloaded for animations like here: https://github.com/openai/procgen/blob/master/procgen/src/games/leaper.cpp#L246 so you either have to leave the frog animation frames or disable animations.

Does that answer your question?

**Comment by KarlXing** [comment]
Thank you for the answer! It solves my question. 

Finally I created new games with fixed assets. Just like in your answer, I modified 'resources.cpp' to allow single-option background image and modify individual game script like 'dodgeball.cpp' to replace multiple image options for entities with only one image option. It works well. Thank you for also pointing out the problem of animation. It's a good answer.

Just providing information for anyone who has the same demand like me, you could look into this commit [https://github.com/KarlXing/procgen/commit/12f63c3989973a069378f4b396ec8794b2e51b28](https://github.com/KarlXing/procgen/commit/12f63c3989973a069378f4b396ec8794b2e51b28) where I created new dodgeball games with fixed and unique visual feature settings.

![image](https://user-images.githubusercontent.com/15907990/75081050-bc6efb80-54c2-11ea-82e3-4f1a9d3429d4.png)
