### ISSUE TITLE
Unsolvable seeds

### ISSUE THREAD

**Issue by KarolisRam** [openai/procgen#59]
After inspecting trained agents and playing the Procgen games myself I noticed some unsolvable seeds/bugs in a few games. The most serious ones were in the Jumper environment, with ~7% of seeds finishing after 1 frame with no reward. 

**Jumper**
Some levels finish in 1 step regardless of action taken, because the agent spawns on top of the goal or enemy. Here's an example to see it in interactive mode (add --record-dir flag if you want a video saved):
`python -m procgen.interactive --distribution-mode easy --vision human --env-name jumper --level-seed 5`

Some pictures to illustrate:
Correct seed. Agent with enemy on one side (level-seed=6):
![image](https://user-images.githubusercontent.com/8534177/98668278-925ab380-2347-11eb-9095-7a189b22859d.png)

Spawning on top of an enemy (level-seed=5):
![image](https://user-images.githubusercontent.com/8534177/98669083-c2568680-2348-11eb-99ea-00d79020c07b.png)

Spawning on top of the goal  (level-seed=9):
![image](https://user-images.githubusercontent.com/8534177/98669113-d0a4a280-2348-11eb-9eee-c49938848f47.png)

I used the following code to calculate the number of seeds suffering from this issue (fix a seed and keep resetting to try out all possible actions to see if you can make the episode last longer than 1 step):

```
import gym


def is_unsolvable(seed):
    env = gym.make("procgen:procgen-jumper-v0", distribution_mode="easy", num_levels=1, start_level=seed)
    for action in range(15):
        env.reset()
        obs, rew, done, info = env.step(action)
        if not done or rew > 0:  # remove the rew > 0 clause to include spawning on top of the goal.
            return False
    return True


c = 0
n = 100000
for seed in range(1, n + 1):
    c += is_unsolvable(seed)
    if seed % 1000 == 0:
        print(c, seed)
```
Out of first 100,000 seeds on easy difficulty 7,820 (7.8%) spawn on top of an enemy, 748 (0.7%) spawn on top of the goal.
On hard difficulty 6,635 (6.6%) spawn on top of an enemy, 140 (0.1%) spawn on top of the goal.
This might explain why a fully trained agent only achieves an average reward of 8 out of 10 even on easy difficulty.

**Bigfish**
Sometimes the agent spawns on the edge of the environment:
![image](https://user-images.githubusercontent.com/8534177/98671080-a0aace80-234b-11eb-8f32-ea9b26bcd6f9.png)
If it moves to the right in this position it will get permanently stuck. If it moves to the left it will escape. You can see this using:
`python -m procgen.interactive --distribution-mode easy --vision human --env-name bigfish --level-seed 24046244`

I don't know how severe this problem is exactly, but I had it happen 3 times in a random sample of 100 easy seeds (24046244, 272366766, 1565904408).

A similar situation can arise when the agent consumes a fish while being next to the top or bottom of the environment. If it grows, it will grow into the edge and will be unable to move left or right.

**Miner**
This doesn't happen often, but here's one example of an impossible seed (easy, 1883496389). The bottom right diamond cannot be reached.
![image](https://user-images.githubusercontent.com/8534177/98673706-a3a7be00-234f-11eb-8b69-d03d4309c99b.png)

**Caveflyer**
Similar to Jumper environment. In 292 (0.3%) out of 100,000 easy seeds and in 410 (0.4%) out of 100,000 hard seeds the agent spawns next to an enemy and dies in 1 step regardless of action taken:
![image](https://user-images.githubusercontent.com/8534177/98675364-10bc5300-2352-11eb-881b-32f812b4e3d8.png)
Interactive code to try it:
`python -m procgen.interactive --distribution-mode easy --vision human --env-name caveflyer --level-seed 1326`

**Comment by christopher-hesse** [comment]
Thanks for the thorough investigation!

The paper says: "The procedural generation in each environment strives to make all levels solvable, but this is not strictly guaranteed. For each environment, greater than 99% of levels are believed to be solvable."  So it sounds like Jumper, at least, does not meet that requirement.

@kcobbe any thoughts?  I think we should make note of this (at least in the README), but changing the generation at this point would make it hard to compare results, since the results would depend on what version of procgen was being used.

**Comment by kcobbe** [comment]
Thank you very much for these detailed notes! I have updated the README to mention these issues.

I agree with @christopher-hesse that we don't currently want to patch these issues, in order to make it easier to compare against results that have already been published. However, it's definitely important to note their existence, particularly in the case of Jumper, which appears to have the most significant bug (in terms of influencing max expected achievable reward).

I appreciate you bringing this to our attention.
