### ISSUE TITLE
Environment with same seed is different in interactive vs gym mode

### ISSUE THREAD

**Issue by zplizzi** [openai/procgen#8]
For the same seed, environments created in interactive mode are completely different than those in library mode in layout. I would have expected them to be the same, and that would be useful so that you can pick out a seed you like in interactive mode and then train the model with that same layout.

Separately, I think it would be nice to have a flag to play interactive mode with the exact same observations as the library mode - ie 64x64 and any other changes that may exist.

`python -m procgen.interactive --env-name caveflyer --level-seed 6`

![image](https://user-images.githubusercontent.com/5598968/70664976-62c79680-1c20-11ea-8f72-47b0e01397c1.png)

```
import procgen
import gym
env = gym.make("procgen:procgen-caveflyer-v0", rand_seed=6)
obs = env.reset()
plt.imshow(obs)
```

![image](https://user-images.githubusercontent.com/5598968/70665169-e3869280-1c20-11ea-9870-25556c8baae5.png)

**Comment by christopherhesse** [comment]
That option should already be in the interactive script: https://github.com/openai/procgen/blob/master/procgen/interactive.py#L53

You are using `rand_seed` instead of `start_level` + `num_levels`.  If you look in the interactive script, `level-seed` just sets `start_level` and `num_levels`: https://github.com/openai/procgen#environment-options

If you set `num_levels` to anything besides `1`, you'll also want to set `rand_seed` if you want to get the same level when you create the environment, otherwise you'll get a random level from the valid level seeds.

**Comment by zplizzi** [comment]
Ahh, makes sense. Thanks!
